name: deploy tickertracker
on:
  push:
    paths:
      - esxwallpapersbucket/tickertracker/**
jobs:
  deploy_tickertracker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: deploy tickertracker
      run: aws s3 sync ./esxwallpapersbucket/ s3://esxwallpapersbucket --delete
