name: deploy esxlambdatickers
on:
  push:
    paths:
      - lambdas/esxlambdatickers/**
jobs:
  deploy_esxlambdatickers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: zip esxlambdatickers
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -g -j lambdas/esxlambdatickers/package.zip lambdas/esxlambdatickers/lambda_function.py
    - name: deploy esxlambdatickers
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: esxlambdatickers
        zip_file: lambdas/esxlambdatickers/package.zip
